import Head from "next/head";

const title = "crash test diaries"

const HeadComponent = () => {
  return (
    <Head>
      <meta
        name='description'
        content=''
      />
      <title>Jen Corbett Developer</title>
      <meta
        name='description'
        content='Generated by create next app'
      />
      <meta
        name='viewport'
        content='width=device-width, initial-scale=1'
      />
      <link
        rel='icon'
        href='/favicon.ico'
      />
      <meta
        name='og:title'
        content={title}
      />
      <meta
        name='twitter:card'
        content='summary_large_image'
      />
    </Head>
  );
};

export default HeadComponent;
