import Head from "next/head";

const title = "Jen Corbett Web Designer and Developer";

const HeadComponent = () => {
  return (
    <Head>
      <meta
        name="description"
        content=""
      />
      <title>{title}</title>
      <meta
        name="description"
        content="Generated by create next app"
      />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
      />
      <link
        rel="icon"
        href="/favicon.ico"
      />
      <meta
        name="og:title"
        content={title}
      />
    </Head>
  );
};

export default HeadComponent;
