import { Html, Head, Main, NextScript } from "next/document";

import HeadComponent from "@components/head";
const title = "Jen Corbett Web Development, Design & Digital Strategy";

export default function Document() {
  return (
    <Html lang="en">
      {" "}
      <Head>
        {" "}
        <meta
          name="description"
          content=""
        />
        <title>{title}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        <meta
          name="og:title"
          content={title}
        />
      </Head>
      <HeadComponent />
      <body>
        {" "}
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
