import Head from "next/head";

import Card from "@components/card";

const title = "Jen Corbett Web Development, Design & Digital Strategy";

const description = {
  text: `I'm a developer based in Ruakākā, Aotearoa NZ. If you would like to say hi or check my availability, feel free to email me on hello[at]jencorbett.dev or reach out on social.`,
};

export default function Home() {
  return (
    <>
      {" "}
      <Head>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <title>{title}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        <meta
          name="og:title"
          content={title}
        />
      </Head>
      <div>
        <section>
          <Card>
            <p> {description.text}</p>
          </Card>
        </section>
      </div>
    </>
  );
}
