import NowPlaying from "@components/player";
import Head from "next/head";
import Card from "@components/card";
import Header from "@components/header";

const title = "Jen Corbett Web Development, Design & Digital Strategy";

export default function Home() {
  return (
    <div>
      <div>
        <Head>
          <meta
            name="description"
            content=""
          />
          <title>{title}</title>
          <meta
            name="description"
            content="Generated by create next app"
          />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1"
          />
          <link
            rel="icon"
            href="/favicon.ico"
          />
          <meta
            name="og:title"
            content={title}
          />
        </Head>
        <Header home />
        <Card>
          <p className={``}>
            I'm a developer and web designer based in Ruakākā, Aotearoa New
            Zealand. To say hi or check my availability, feel free to reach out
            to me on your social channel of choice or email me on
            hello[at]jencorbett.dev.
          </p>
          <NowPlaying />
        </Card>
      </div>
    </div>
  );
}
